[package]
name = "keplerian-sim-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo-timers = { version = "0.3.0", features = ["futures"] }
glow = "0.14.2"
keplerian_sim = "0.4.0"
three-d = "0.18.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "WebGl2RenderingContext", "Window", "console"] }

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
lto = "fat"
debug = false
strip = true
