[build]
minify = "on_release"
public_url = "."

[serve]
addresses = ["::1"]

[[hooks]]
stage = "pre_build"
command = "bun"
command_arguments = [
    "build",
    "--production",
    "--minify",
    "--outfile=assets/watchdog.js",
    "assets/watchdog.ts",
]

[watch]
ignore = ["assets/watchdog.js"]
